name: Urban Stitch

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with Black
      id: black_check
      run: |
        echo "Checking formatting..."
        if ! black --check .; then
          echo "::warning::Code is not formatted properly. Will auto-format next."
          echo "formatted=false" >> $GITHUB_OUTPUT
        else
          echo "formatted=true" >> $GITHUB_OUTPUT
        fi
    - name: Auto-format with Black
      if: steps.black_check.outputs.formatted == 'false'
      run: |
        echo "Auto-formatting with Black..."
        black .
    - name: Commit and push formatted code
      if: steps.black_check.outputs.formatted == 'false'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "chore: auto-format code via GitHub Actions" || echo "No changes to commit"
        git push